//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResErrors", typeof(ResErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Password!.
        /// </summary>
        public static string ErrorPasswordIncorrect {
            get {
                return ResourceManager.GetString("ErrorPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already logged in!.
        /// </summary>
        public static string ErrorUserIsAlreadyLoggedIn {
            get {
                return ResourceManager.GetString("ErrorUserIsAlreadyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username does not exist!.
        /// </summary>
        public static string ErrorUsernameDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorUsernameDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This player is already loaded.
        /// </summary>
        public static string PlayerAlreadyLoaded {
            get {
                return ResourceManager.GetString("PlayerAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is invalid.
        /// </summary>
        public static string RegisterEmailInvalid {
            get {
                return ResourceManager.GetString("RegisterEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password! Password requirements are as follows:
        ///- Between 8 and 32 characters long
        ///- Contain a lower case letter
        ///- Contain a upper case letter
        ///- Contain a number
        ///- Contain a special character
        ///- Contain no whitespace.
        /// </summary>
        public static string RegisterPasswordInvalid {
            get {
                return ResourceManager.GetString("RegisterPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is too short, must be at least 3 characters long!.
        /// </summary>
        public static string RegisterUsernameInvalid {
            get {
                return ResourceManager.GetString("RegisterUsernameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character does not exist for this user.
        /// </summary>
        public static string UserCharacterDoesNotExist {
            get {
                return ResourceManager.GetString("UserCharacterDoesNotExist", resourceCulture);
            }
        }
    }
}
